# Snowflake Credentials
[snowflake]
user = "HEADOFNICKEL"
password = "Dataisbeautifulrev001!"
account = "https://kbqpjgp-ba09670.snowflakecomputing.com"
database = "FMS_DB"
schema = "PUBLIC"

# SQL Server Credentials
[sqlserver]
server = "10.211.10.2"
database = "FMS_DB"
username = "headofnickel"
password = "Dataisbeautifulrev001!"
