[sql]
# Update server details with your deployment SQL Server info
host = "10.211.10.2"     # Replace with your SQL Server hostname or IP
port = 1433                  # Standard SQL Server port
database = "FMS_DB"          # Your database name
username = "headofnickel"   # Replace with the correct SQL login
password = "Dataisbeautifulrev001!"   # Replace with the correct password
driver = "ODBC Driver 17 for SQL Server"

# You can also use Windows Authentication by setting:
# trusted_connection = "yes"
# And then you can omit the username and password 